/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Lodge {
  id: string;
  name: string;
  number: number;
  address: string;
  city: string;
  meetingDay: string;
  ritual: string;
  phone?: string;
  image?: string;
}

export interface NewsItem {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  image?: string;
  content: string;
}

export interface EventItem {
  id: string;
  title: string;
  date: string;
  location: string;
  type: 'Ritualística' | 'Social' | 'Palestra' | 'Administrativa';
  description: string;
  responsibleLodge: string;
  participatingLodges: string;
  speaker?: string;
  image?: string;
}

export interface Speaker {
  id: string;
  name: string;
  title: string;
  bio: string;
  lectures: string[];
  image?: string;
}

export const APP_CONFIG = {
  logo: '/assets/logo/logo.png', // User can upload to /public/assets/logo/logo.png
};

export const LODGES: Lodge[] = [
  {
    id: '1',
    name: 'Acácia Sorocabana',
    number: 97,
    address: 'R. Miranda Azevedo, 373',
    city: 'Sorocaba',
    meetingDay: 'Quarta-feira',
    ritual: 'REAA',
    phone: '(15) 98100-7175',
  },
  {
    id: '2',
    name: 'Harmonia e Trabalho',
    number: 222,
    address: 'R. Alberto Leme Cavalheiro, 524',
    city: 'Itapetininga',
    meetingDay: 'Segunda-feira',
    ritual: 'REAA',
    phone: '(15) 99704-6904',
  },
  {
    id: '3',
    name: 'Colunas de Piedade',
    number: 245,
    address: 'R. Porfirio Flora, 77',
    city: 'Piedade',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(15) 99620-7788',
  },
  {
    id: '4',
    name: 'União Fraternal',
    number: 301,
    address: 'R. Dr. Alfredo Maia, 286',
    city: 'Votorantim',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(15) 99146-3128',
  },
  {
    id: '5',
    name: 'Fraternidade de Sorocaba',
    number: 383,
    address: 'Av. dos Bandeirantes, 750',
    city: 'Sorocaba',
    meetingDay: 'Terça-feira',
    ritual: 'REAA',
    phone: '(15) 99111-0300',
  },
  {
    id: '6',
    name: 'Fraternidade Acaciana',
    number: 398,
    address: 'Av. dos Bandeirantes, 750',
    city: 'Sorocaba',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(15) 99777-5440',
  },
  {
    id: '7',
    name: 'Manchester Paulista',
    number: 413,
    address: 'Pça. Berlim, 77',
    city: 'Sorocaba',
    meetingDay: 'Sexta-feira',
    ritual: 'REAA',
    phone: '(15) 99774-1668',
  },
  {
    id: '8',
    name: 'Colunas de São Roque',
    number: 446,
    address: 'R. Barão de Piratininga, 91',
    city: 'São Roque',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(11) 99717-7601',
  },
  {
    id: '9',
    name: 'Saber Fraterno',
    number: 499,
    address: 'R. Almir Beneti, 172',
    city: 'Sorocaba',
    meetingDay: 'Sexta-feira',
    ritual: 'Emulação',
    phone: '(15) 99786-7313',
  },
  {
    id: '10',
    name: 'Abolição',
    number: 552,
    address: 'R. Treze de Maio, 1008',
    city: 'Tatuí',
    meetingDay: 'Quarta-feira',
    ritual: 'REAA',
    phone: '(15) 98162-4318',
  },
  {
    id: '11',
    name: 'Fidelidade e Justiça',
    number: 565,
    address: 'R. Visconde do Rio Branco, 100',
    city: 'Sorocaba',
    meetingDay: 'Quarta-feira',
    ritual: 'Emulação',
    phone: '(15) 99755-9528',
  },
  {
    id: '12',
    name: '11 de Agosto',
    number: 627,
    address: 'Av. Donato Flores, 1128',
    city: 'Tatuí',
    meetingDay: 'Quinta-feira',
    ritual: 'Emulação',
    phone: '(15) 99804-6657',
  },
  {
    id: '13',
    name: 'Libertas de Salto',
    number: 637,
    address: 'R. das Avencas, 178',
    city: 'Salto',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(11) 94718-5752',
  },
  {
    id: '14',
    name: 'Elo Dourado Sorocaba',
    number: 648,
    address: 'R. João Ribeiro de Barros, 999',
    city: 'Sorocaba',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(15) 99145-8968',
  },
  {
    id: '15',
    name: 'Justa e Perfeita Loja de São João',
    number: 680,
    address: 'Rod. Raposo Tavares, km 90',
    city: 'Sorocaba',
    meetingDay: 'Quarta-feira',
    ritual: 'Schroder',
    phone: '(15) 99742-9341',
  },
  {
    id: '16',
    name: 'Luz, Vida e Amor',
    number: 690,
    address: 'Av. dos Crisântemos, 287',
    city: 'Sorocaba',
    meetingDay: 'Terça-feira',
    ritual: 'REAA',
    phone: '(15) 99778-4962',
  },
  {
    id: '17',
    name: 'Discípulos de Adonhiram',
    number: 729,
    address: 'R. Prof. Hortência Soares do Amaral, 665',
    city: 'Sorocaba',
    meetingDay: 'Terça-feira',
    ritual: 'Adonhiramita',
    phone: '(15) 99789-0000',
  },
  {
    id: '18',
    name: 'Colunas do Templo de Salomão',
    number: 738,
    address: 'Av. dos Bandeirantes, 750',
    city: 'Sorocaba',
    meetingDay: 'Segunda-feira',
    ritual: 'Emulação',
    phone: '(15) 99118-6128',
  },
  {
    id: '19',
    name: 'André Luiz',
    number: 766,
    address: 'Pça. Berlim, 77',
    city: 'Sorocaba',
    meetingDay: 'Segunda-feira',
    ritual: 'REAA',
    phone: '(15) 99773-0938',
  },
  {
    id: '20',
    name: 'Colunas de Ipanema',
    number: 799,
    address: 'R. Prof. Daniel Pereira do Nascimento, 25',
    city: 'Sorocaba',
    meetingDay: 'Segunda-feira',
    ritual: 'REAA',
    phone: '(15) 99777-8581',
  },
  {
    id: '21',
    name: 'Jacques du Bourgogne DeMolay',
    number: 806,
    address: 'R. Professora Guida Mares, 230',
    city: 'Sorocaba',
    meetingDay: 'Quinta-feira',
    ritual: 'Emulação',
    phone: '(15) 99783-1006',
  },
  {
    id: '22',
    name: 'Tropeiros de Sorocaba',
    number: 824,
    address: 'R. Joao Ferreira da Silva, 656',
    city: 'Sorocaba',
    meetingDay: 'Segunda-feira',
    ritual: 'REAA',
    phone: '(15) 99789-7444',
  },
  {
    id: '23',
    name: 'Confidência',
    number: 825,
    address: 'R. Miranda Azevedo, 373',
    city: 'Sorocaba',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(15) 97403-0670',
  },
  {
    id: '24',
    name: '25 de Julho',
    number: 837,
    address: 'R. Hermelino Matarazzo, 158',
    city: 'Sorocaba',
    meetingDay: 'Terça-feira',
    ritual: 'York',
    phone: '(15) 98139-0003',
  },
  {
    id: '25',
    name: 'União Paulista Itapetininga',
    number: 879,
    address: 'R. Monsenhor Soares, 1063',
    city: 'Itapetininga',
    meetingDay: 'Segunda-feira',
    ritual: 'REAA',
    phone: '(15) 99789-4776',
  },
  {
    id: '26',
    name: 'União e Firmeza Capão Bonito',
    number: 897,
    address: 'R. Marui Ferrari, 33',
    city: 'Capão Bonito',
    meetingDay: 'Quarta-feira',
    ritual: 'REAA',
    phone: '(15) 99775-0442',
  },
  {
    id: '27',
    name: '15 de Agosto',
    number: 900,
    address: 'R. Professora Guida Mares, 230',
    city: 'Sorocaba',
    meetingDay: 'Quarta-feira',
    ritual: 'York',
    phone: '(15) 99716-5374',
  },
  {
    id: '28',
    name: 'Fidelidade e Harmonia',
    number: 904,
    address: 'R. João Leite, 305, sala 9',
    city: 'Boituva',
    meetingDay: 'Quinta-feira',
    ritual: 'Emulação',
    phone: '(15) 99731-0144',
  },
  {
    id: '29',
    name: 'Phoenix',
    number: 911,
    address: 'Pça. Berlim, 77',
    city: 'Sorocaba',
    meetingDay: 'Quinta-feira',
    ritual: 'REAA',
    phone: '(15) 99700-5070',
  },
];

export const NEWS: NewsItem[] = [
  {
    id: '1',
    title: 'Nova Gestão Projeta Avanços para o Colégio',
    excerpt: 'A nova diretoria do Colégio de Lojas da região de Sorocaba tomou posse nesta última semana.',
    date: '15 de Maio, 2026',
    image: 'https://images.unsplash.com/photo-1541410945376-a7872f53434d?auto=format&fit=crop&q=80',
    content: 'O Colégio de Lojas MAÇÔNICAS da Região de Sorocaba deu início a uma nova etapa em sua trajetória com a posse da nova diretoria. O foco principal será a integração das lojas e o fomento à educação maçônica através de novos ciclos de palestras.',
  },
  {
    id: '2',
    title: 'Campanha de Arrecadação de Inverno',
    excerpt: 'Lojas da região se unem para arrecadar agasalhos e cobertores para comunidades carentes.',
    date: '10 de Maio, 2026',
    image: 'https://images.unsplash.com/photo-1541410945376-a7872f53434d?auto=format&fit=crop&q=80',
    content: 'Em uma demonstração de fraternidade e caridade, as lojas participantes do colégio iniciaram a campanha anual de inverno. As doações podem ser entregues em qualquer uma das lojas participantes até o final do mês.',
  },
  {
    id: '3',
    title: 'Seminário de Instrução Maçônica',
    excerpt: 'Mais de 200 irmãos participaram do seminário realizado no último sábado em Sorocaba.',
    date: '05 de Maio, 2026',
    image: 'https://images.unsplash.com/photo-1541410945376-a7872f53434d?auto=format&fit=crop&q=80',
    content: 'O seminário contou com a participação de diversos palestrantes renomados que abordaram temas como a história do rito e sua aplicação na vida cotidiana do maçom contemporâneo.',
  },
];

export const EVENTS: EventItem[] = [
  {
    id: '1',
    title: '25ª Parmegiana de Filé Mignon',
    date: '29/03/2026',
    location: 'Fraternidade de Sorocaba',
    type: 'Social',
    description: 'Tradicional evento beneficente.',
    responsibleLodge: 'ARLS Fraternidade de Sorocaba nº 383',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '2',
    title: '21ª Bacalhoada',
    date: '03/04/2026',
    location: 'Elo Dourado Sorocaba',
    type: 'Social',
    description: 'Evento social beneficente em prol das obras assistenciais.',
    responsibleLodge: 'ARLS Elo Dourado Sorocaba nº 648',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '3',
    title: '2ª Feijoada',
    date: '12/04/2026',
    location: 'Tropeiros de Sorocaba',
    type: 'Social',
    description: 'Segunda edição da feijoada organizada pela ARLS Tropeiros de Sorocaba.',
    responsibleLodge: 'ARLS Tropeiros de Sorocaba nº 824',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '4',
    title: '14º Porco Paraguaio',
    date: '26/04/2026',
    location: 'Fraternidade Acaciana',
    type: 'Social',
    description: 'Evento tradicional da ARLS Fraternidade Acaciana.',
    responsibleLodge: 'ARLS Fraternidade Acaciana nº 398',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '5',
    title: 'Feijoada',
    date: '16/05/2026',
    location: 'Justa e Perfeita Loja de São João',
    type: 'Social',
    description: 'Feijoada beneficente da ARLS Justa e Perfeita Loja de São João.',
    responsibleLodge: 'ARLS Justa e Perfeita Loja de São João nº 680',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '6',
    title: 'Feira Nacional de Cutelaria',
    date: '16 e 17/05/2026',
    location: 'Instituto Humberto de Campos',
    type: 'Social',
    description: 'Feira Nacional de Cutelaria com diversos expositores.',
    responsibleLodge: 'Não informado na arte',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '7',
    title: 'Mineirice',
    date: '17/05/2026',
    location: 'União Fraternal',
    type: 'Social',
    description: 'Evento gastronômico organizado pela ARLS União Fraternal.',
    responsibleLodge: 'ARLS União Fraternal nº 301',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '8',
    title: 'Festa Junina de Votorantim — Festival de Prêmios',
    date: '21/05 a 21/06/2026',
    location: 'Praça de Eventos de Votorantim',
    type: 'Social',
    description: 'Grande festival de prêmios durante a Festa Junina de Votorantim.',
    responsibleLodge: 'ARLS União Fraternal nº 301',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '9',
    title: 'Jantar do Queijo e Vinho',
    date: '22/05/2026',
    location: 'União Fraternal',
    type: 'Social',
    description: 'Jantar especial de Queijo e Vinho organizado pela ARLS União Fraternal.',
    responsibleLodge: 'ARLS União Fraternal nº 301',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
  {
    id: '10',
    title: 'Sessão Conjunta',
    date: '25/05/2026 — 20h',
    location: 'Rua Alberto Leme Cavalheiro, 524 — Itapetininga',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS Harmonia e Trabalho nº 222',
    participatingLodges: 'ARLS Fidelidade nº 931; ARLS União Paulista Itapetininga nº 879',
    speaker: 'Roberto Hathner, Grande Secretário da Cultura',
  },
  {
    id: '11',
    title: 'Sessão Conjunta',
    date: '25/05/2026 — 20h',
    location: 'Templo da Constância — Rua Prof. Daniel Pereira do Nascimento, 25 — Sorocaba',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS Colunas de Ipanema nº 799',
    participatingLodges: 'ARLS Colunas de Salomão nº 738; ARLS André Luiz nº 766; ARLS Tropeiros de Sorocaba nº 824',
    speaker: 'Andrea Ceresa, Grande Secretário de Assuntos Institucionais',
  },
  {
    id: '12',
    title: 'Sessão Conjunta',
    date: '26/05/2026 — 20h',
    location: 'Templo da Fraternidade Acaciana — Av. Bandeirantes, 886, 750 — Sorocaba',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS Fraternidade de Sorocaba nº 383',
    participatingLodges: 'ARLS 4 de Julho nº 859; ARLS 25 de Julho nº 837; ARLS Discípulos de Adonhiram nº 729; ARLS Luz, Vida e Amor nº 690',
    speaker: 'Luiz Cesar Nitsche, 2º Grande Vigilante — palestra: "Entre a razão e as paixões: os passos do Maçom"',
  },
  {
    id: '13',
    title: 'Sessão Conjunta',
    date: '27/05/2026 — 20h',
    location: 'Rodovia Raposo Tavares, km 90 — Sorocaba',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS Justa e Perfeita Loja de São João nº 680',
    participatingLodges: 'ARLS Fidelidade e Justiça nº 565; ARLS Justiça e Liberdade nº 830',
    speaker: 'Luiz Eduardo Montello, 1º Grande Vigilante — palestra: "Platão e a Maçonaria / O Justo e o Perfeito"; presença de Eduardo Fondello, Grande Secretário das Comunicações',
  },
  {
    id: '14',
    title: 'Sessão Conjunta',
    date: '27/05/2026 — 20h',
    location: 'Rua Miranda Azevedo, 373 — Centro — Sorocaba',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS Acácia Sorocabana nº 97',
    participatingLodges: 'ARLS 15 de Agosto nº 900; ARLS Gotthold Ephraim Lessing nº 930',
    speaker: 'Marcos Pelizzon, Grande Hospitaleiro',
  },
  {
    id: '15',
    title: 'Sessão Conjunta',
    date: '27/05/2026 — 20h',
    location: 'Rua Marui Ferrari, 33 — Capão Bonito',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS União e Firmeza nº 897',
    participatingLodges: 'ARLS Acácia de Apiaí nº 924',
    speaker: 'Claudio Roberto, Grande Secretário das Ordens Colaterais',
  },
  {
    id: '16',
    title: 'Sessão Conjunta',
    date: '28/05/2026 — 20h',
    location: 'Templo da Colunas de São Roque',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS Pedra Fundamental nº 780',
    participatingLodges: 'ARLS Colunas de São Roque nº 446; ARLS Alvorecer de Ibiúna nº 362;',
  },
  {
    id: '17',
    title: 'Sessão Conjunta',
    date: '28/05/2026 — 20h',
    location: 'Templo da Fraternidade Acaciana',
    type: 'Ritualística',
    description: 'Sessão conjunta com diversas lojas da região.',
    responsibleLodge: 'ARLS Fraternidade Acaciana nº 398',
    participatingLodges: 'ARLS Libertas de Salto nº 637',
    speaker: 'Apresentação da Sessão do Oriente Eterno, rito criado pela Libertas de Salto',
  },
  {
    id: '18',
    title: 'Sessão de Encerramento da 1ª Semana de Lojas Conjuntas da 11ª Região',
    date: '29/05/2026 — 20h',
    location: 'Templo da Fraternidade Acaciana',
    type: 'Ritualística',
    description: 'Sessão de Encerramento da 1ª Semana de Lojas Conjuntas da 11ª Região.',
    responsibleLodge: 'ARLS Manchester Paulista nº 413',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
    speaker: 'Jorge Anysio Haddad, Sereníssimo Grão-Mestre da GLESP',
  },
  {
    id: '19',
    title: 'I Simpósio da Nova Gestão 2026–2027 — 11ª Região',
    date: '30/05/2026 — 8h30',
    location: 'Colégio O Farol — Rua Aparecida, 1388 — Sorocaba',
    type: 'Administrativa',
    description: 'I Simpósio da Nova Gestão 2026–2027 da 11ª Região.',
    responsibleLodge: '11ª Região da GLESP',
    participatingLodges: 'Novas administrações das Lojas 2026–2027',
    speaker: 'Marcel Marangon, Adriano Paparelli, Roberto Nincao, Francisco Cortes, Cesar Augusto Garcia',
  },
  {
    id: '20',
    title: 'Jantar Ritualístico — Novos Veneráveis',
    date: '26/06/2026',
    location: 'Salão da Fraternidade Acaciana',
    type: 'Ritualística',
    description: 'Jantar Ritualístico em comemoração aos Novos Veneráveis.',
    responsibleLodge: 'ARLS Tropeiros de Sorocaba nº 824',
    participatingLodges: 'Todas as Lojas da 11ª Região convocadas',
  },
];

export const SPEAKERS: Speaker[] = [
  {
    id: '1',
    name: 'Ir. Luiz Alberto Borrelli Cerqueira',
    title: 'ARLS Libertas de Salto 637',
    bio: 'Palestrante experiente com foco em Astronomia, Música, Saúde e Ufologia dentro do contexto maçônico.',
    lectures: [
      'Astronomia - As muitas casas de meu Pai',
      'Música - A importância da Música na Egrégora da Loja',
      'Saúde - A Influência dos Chakras na Saúde Física',
      'Ufologia - Historia e Perspectivas do Contato Ufológico',
      'Quem é o Pai? Um estudo sobre a Divindade',
      'Vencer minhas Paixoes, Submeter minha Vontade... Contribuições da Neuropsicologia',
    ],
  },
  {
    id: '2',
    name: 'Ir. Aldren Moraes',
    title: 'ARLS Tropeiros de Sorocaba 824',
    bio: 'Especialista em simbolismo e arquitetura do templo.',
    lectures: [
      'A Aboboda Celeste',
    ],
  },
  {
    id: '3',
    name: 'Ir. Felipe Mello',
    title: 'ARLS Tropeiros de Sorocaba 824',
    bio: 'Pesquisador de história e ritos maçônicos, com vasta gama de temas sobre arquitetura e moral.',
    lectures: [
      'A Obra Inacabada',
      'A Arquitetura da Virtude',
      'As Cruzadas pelo olhar arabe',
      'A Guerra Secular entre o Altar e a Loja',
      'Arquitetura Secreta da Independencia',
      'Gestão Maçonica',
      'Moral e Principios: O que significa fazer a coisa certa?',
    ],
  },
  {
    id: '4',
    name: 'Ir. Luiz Cesar Nitsche',
    title: 'ARLS Fraternidade de Sorocaba 383',
    bio: 'Filósofo e pesquisador, aborda temas que cruzam a maçonaria com a filosofia clássica e simbolismo animal.',
    lectures: [
      'Entre a razão e as paixões: os passos do Maçom',
      'Rito Escocês: Abertura e fechamento e suas várias faces',
      'Circulação em Loja e seus significados.',
      'Pensando a liberdade: Entre Descartes e Espinoza',
      'A moral Kantiana e a moral Maçônica: convergências e divergências',
      'Maçonaria: Entre o esotérico e o exotérico',
    ],
  },
  {
    id: '5',
    name: 'Ir. Ricardo Strangis Cumino',
    title: 'ARLS Discipulos de Adonhiram 729',
    bio: 'Historiador especializado na história da maçonaria internacional.',
    lectures: [
      'Maçonaria na Alemanha no Pós-Guerra',
    ],
  },
  {
    id: '6',
    name: 'Ir. Eduardo do Amaral Junior',
    title: 'ARLS Jacques Du Boutgogne DeMolay 806',
    bio: 'Especialista em rituais e instrução maçônica.',
    lectures: [
      'Entendendo o Ritual de Emulação',
    ],
  },
  {
    id: '7',
    name: 'Ir. Claudio Roberto Silva',
    title: 'ARLS Fidelidade e Justiça 565',
    bio: 'Pesquisador de ordens colaterais e ritos ingleses.',
    lectures: [
      'Ordens Colateriais Inglesas',
    ],
  },
];
